# Generated by Django 3.0.4 on 2020-03-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('date_of_employment', models.DateTimeField(verbose_name='Employment Date')),
                ('department', models.CharField(max_length=40)),
                ('position', models.CharField(max_length=40)),
                ('image_url', models.CharField(max_length=2083)),
                ('salary', models.IntegerField()),
                ('working_history', models.CharField(max_length=5000)),
                ('employment_position', models.CharField(max_length=40)),
                ('day_offs', models.IntegerField()),
                ('personal_number', models.IntegerField(max_length=11)),
                ('email', models.CharField(max_length=40)),
                ('mobile_number', models.IntegerField()),
            ],
        ),
    ]
