# Generated by Django 3.0.4 on 2020-03-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pension_fund',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile_number',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_number',
            field=models.CharField(max_length=11),
        ),
    ]
