# Generated by Django 3.0.4 on 2020-03-20 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20200320_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='image_url',
        ),
    ]
